# Generated by Django 4.1.5 on 2023-03-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='rewards/'),
        ),
        migrations.AlterField(
            model_name='rewardclaim',
            name='claim_qr',
            field=models.FileField(blank=True, upload_to='rewards/'),
        ),
    ]
