# Generated by Django 4.1.5 on 2023-03-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='code_type',
            field=models.CharField(choices=[('qr', 'QR Code'), ('random', 'Randomly Generated Code'), ('manual', 'Manually Input Code')], default='random', max_length=6),
        ),
    ]
