# Generated by Django 4.1.5 on 2023-03-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='streak',
            name='last_login_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
