# Generated by Django 4.1.5 on 2023-03-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(blank=True, choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly')], null=True)),
                ('subscriptions', models.ManyToManyField(blank=True, to='minted.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='notification_subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minted.notificationsubscription'),
        ),
    ]
