# Generated by Django 4.1.5 on 2023-03-15 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='reward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='minted.reward'),
        ),
    ]
