# Generated by Django 4.1.5 on 2023-03-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_login_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
