# Generated by Django 4.1.5 on 2023-02-27 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_time', models.DateTimeField(blank=True)),
                ('streak', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='streak_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='minted.streak'),
        ),
    ]
