# Generated by Django 4.1.5 on 2023-02-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='user',
        ),
    ]
