# Generated by Django 4.1.5 on 2023-02-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('timeframe', models.CharField(blank=True, choices=[('/week', 'week'), ('/month', 'month'), ('/quarter', 'quarter'), ('/year', 'year')], max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minted.spendinglimit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minted.spendinglimit'),
        ),
    ]
