# Generated by Django 4.1.5 on 2023-03-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
