# Generated by Django 4.1.5 on 2023-03-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='reward_title',
        ),
    ]
