# Generated by Django 4.1.5 on 2023-02-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0002_streak_user_streak_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='streak_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minted.streak'),
        ),
    ]
