# Generated by Django 4.1.5 on 2023-03-19 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0002_alter_reward_code_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='user_limit',
            field=models.IntegerField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='code_type',
            field=models.CharField(choices=[('qr', 'QR Code'), ('random', 'Randomly Generated Code')], default='random', max_length=6),
        ),
    ]
