# Generated by Django 4.1.5 on 2023-03-12 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0002_remove_reward_reward_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='claim_code',
        ),
        migrations.AddField(
            model_name='reward',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('reward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minted.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
