# Generated by Django 4.1.5 on 2023-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0002_remove_expenditure_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendinglimit',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
