# Generated by Django 4.1.5 on 2023-03-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0002_alter_streak_last_login_time'),
        ('minted', '0002_remove_friendrequest_is_active'),
    ]

    operations = [
    ]
