# Generated by Django 4.1.5 on 2023-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0002_alter_streak_last_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_login_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
