# Generated by Django 4.1.5 on 2023-03-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0003_alter_rewardclaim_reward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='code_type',
            field=models.CharField(choices=[('qr', 'QR Code'), ('random', 'Randomly Generated Code')], default='random', max_length=6),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='claim_qr',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='rewardclaim',
            name='claim_code',
            field=models.CharField(blank=True, default='0', max_length=10, unique=True),
        ),
    ]
