# Generated by Django 4.1.5 on 2023-03-19 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0003_reward_user_limit_alter_reward_code_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='user_limit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
