# Generated by Django 4.1.5 on 2023-02-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0003_alter_user_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendinglimit',
            name='timeframe',
            field=models.CharField(choices=[('/week', 'week'), ('/month', 'month'), ('/quarter', 'quarter'), ('/year', 'year')], max_length=11),
        ),
    ]
