# Generated by Django 4.1.5 on 2023-03-12 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0003_remove_reward_claim_code_reward_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
