# Generated by Django 4.1.5 on 2023-03-19 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0004_alter_reward_user_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='user_limit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
