# Generated by Django 4.1.5 on 2023-03-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0004_alter_streak_last_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='streak_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minted.streak'),
        ),
    ]
