# Generated by Django 4.1.5 on 2023-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0004_reward_code_type_rewardclaim_claim_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='claim_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
