# Generated by Django 4.1.5 on 2023-02-06 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0004_alter_expenditure_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('timeframe', models.CharField(choices=[('/week', 'Weekly'), ('/month', 'Monthly'), ('/6 months', 'Half-yearly'), ('/year', 'Annually')], max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='minted.spendinglimit'),
        ),
    ]
