# Generated by Django 4.1.5 on 2023-03-12 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0004_alter_rewardclaim_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
