# Generated by Django 4.1.5 on 2023-02-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0005_spendinglimit_alter_category_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
