# Generated by Django 4.1.5 on 2023-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0005_alter_rewardclaim_claim_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='claim_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
