# Generated by Django 4.1.5 on 2023-03-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0005_alter_rewardclaim_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='claim_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
