# Generated by Django 4.1.5 on 2023-03-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0007_remove_points_user_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='minted.points'),
        ),
    ]
