# Generated by Django 4.1.5 on 2023-02-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0007_alter_category_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='minted.spendinglimit'),
            preserve_default=False,
        ),
    ]
