# Generated by Django 4.1.5 on 2023-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0007_alter_user_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendinglimit',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='timeframe',
            field=models.CharField(choices=[('/week', 'week'), ('/month', 'month'), ('/quarter', 'quarter'), ('/year', 'year')], default='/week', max_length=11),
        ),
    ]
