# Generated by Django 4.1.5 on 2023-02-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0008_alter_spendinglimit_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendinglimit',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='timeframe',
            field=models.CharField(choices=[('/week', 'week'), ('/month', 'month'), ('/quarter', 'quarter'), ('/year', 'year')], max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minted.spendinglimit'),
        ),
    ]
