# Generated by Django 4.1.5 on 2023-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0011_alter_user_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendinglimit',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='timeframe',
            field=models.CharField(choices=[('/week', 'week'), ('/month', 'month'), ('/quarter', 'quarter'), ('/year', 'year')], max_length=11),
        ),
    ]
