# Generated by Django 4.1.5 on 2023-03-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0002_subscription_notificationsubscription_and_more'),
        ('minted', '0011_points_alter_user_points'),
    ]

    operations = [
    ]
