# Generated by Django 4.1.5 on 2023-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0012_spendinglimit_remaining_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendinglimit',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=None, max_digits=12), max_digits=12),
        ),
    ]
