# Generated by Django 4.1.5 on 2023-02-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0016_alter_spendinglimit_remaining_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spendinglimit',
            name='limit',
        ),
        migrations.AddField(
            model_name='spendinglimit',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='spendinglimit',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='timeframe',
            field=models.CharField(blank=True, choices=[('/week', 'week'), ('/month', 'month'), ('/quarter', 'quarter'), ('/year', 'year'), ('manual', 'manual')], max_length=11),
        ),
    ]
