# Generated by Django 4.1.5 on 2023-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0019_alter_category_budget_alter_user_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendinglimit',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
    ]
