# Generated by Django 4.1.5 on 2023-02-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0002_alter_category_budget'),
        ('minted', '0020_spendinglimit_budget'),
    ]

    operations = [
    ]
