# Generated by Django 4.1.5 on 2023-02-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0021_merge_20230222_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spendinglimit',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='spendinglimit',
            name='remaining_budget',
        ),
        migrations.RemoveField(
            model_name='spendinglimit',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minted.spendinglimit'),
        ),
    ]
