# Generated by Django 4.1.5 on 2023-02-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0022_remove_spendinglimit_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='minted.spendinglimit'),
            preserve_default=False,
        ),
    ]
