# Generated by Django 4.1.5 on 2023-02-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minted', '0023_alter_category_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='budget',
        ),
    ]
