# Generated by Django 4.1.5 on 2023-01-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PST', '0003_spendinglimit_alter_category_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spendinglimit',
            old_name='time',
            new_name='timeframe',
        ),
    ]
