# Generated by Django 4.1.5 on 2023-01-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PST', '0004_alter_category_expenditures_alter_expenditure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expenditures',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PST.category'),
        ),
    ]
